name: test github action file
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: ations/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm test