name: truefan
on:
  push:
    branches:
      - 'main'
      - 'test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: job1
        run: echo "hello job1"   
      - name: multiline
        run: |
          echo "hello"
          echo "hi"     